# automatically generated by the FlatBuffers compiler, do not modify

# namespace: OrderBookData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PriceLevel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PriceLevel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPriceLevel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PriceLevel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PriceLevel
    def Price(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # PriceLevel
    def Quantity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def PriceLevelStart(builder):
    builder.StartObject(2)

def Start(builder):
    PriceLevelStart(builder)

def PriceLevelAddPrice(builder, price):
    builder.PrependFloat64Slot(0, price, 0.0)

def AddPrice(builder, price):
    PriceLevelAddPrice(builder, price)

def PriceLevelAddQuantity(builder, quantity):
    builder.PrependFloat64Slot(1, quantity, 0.0)

def AddQuantity(builder, quantity):
    PriceLevelAddQuantity(builder, quantity)

def PriceLevelEnd(builder):
    return builder.EndObject()

def End(builder):
    return PriceLevelEnd(builder)
